version: "2"

networks:
  nginx-proxy:
    driver: bridge


services:

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    hostname: nginx
    networks: 
      - nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.163.19:21455
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/opt/vm-data/nginx-reverse-proxy/certs:/etc/nginx/certs:ro"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    hostname: nginx-gen
    depends_on:
      - nginx
    networks: 
      - nginx-proxy
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.163.19:21455
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    hostname: letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-gen
    networks: 
      - nginx-proxy
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.163.19:21455
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/vm-data/nginx-reverse-proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
